# Routing

## Общее поведение

Для объявления функции - обработчика сообщений брокера необходимо использовать декоратор `@broker.handle`

```python
@broker.handle("test")
async def base_handler(body: str):
    ...
```

Это поведение схоже для всех брокеров, однако, параметры, передаваемые в `@broker.handle` - являются специфичными для каждого брокера.

Чтобы узнать подробнее о поведении специализированных брокеров перейдите в следующие разделы:

* [RabbitBroker](../../../rabbit/1_routing)
* [NatsBroker](../../../nats/2_routing)

## Обработка ошибок

Однако, все брокеры имеют в методе `@broker.hanle` флаг `retry`, который отвечает за логику обработки ошибок.

По умолчанию этот флаг имеет значение `False`, который говорит о том, что если в ходе обработки сообщения возникла ошибка, оно все равно будет извлечено из очереди.

```python
@broker.handle("test", retry=False)  # не обрабатывать исключения
async def base_handler(body: str):
    ...
```

При установке этого флага в `True` сообщение будет помещаться обратно в очередь при возникновении ошибки бесконечно. При этом сообщение может уйти в обработку как другому потребителю (если их несколько), так и тому же самому.

```python
@broker.handle("test", retry=True)  # пробовать заново бесконечно
async def base_handler(body: str):
    ...
```

При установке в качестве флага значения `int`, количество повторных попыток будет ограничено этим числом.
```python
@broker.handle("test", retry=3)     # сделать до 3ех попыток
async def base_handler(body: str):
    ...
```

!!! bug
    На данный момент учитываются попытки только в рамках текущего потребителя. Если сообщение уйдет другому потребителю, у того будет свой счетчик.
    Впоследствии эта логика будет переработана.

!!! tip
    Для более сложных вариантов обработки ошибок вы можете использовать [tenacity](https://tenacity.readthedocs.io/en/latest/){.external-link target="_blank"}